<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cicshorturls"
 *
 * Auto generated by Extension Builder 2016-01-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Short URLs',
	'description' => 'Configure short URLs for pages',
	'category' => 'misc',
	'author' => 'Gabe Blair',
	'author_email' => 'gabe@castironcoding.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'realurl' => '1.12.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
